version: '2'
services:

  esmaster:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - cluster.name=heisenbug
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - node.max_local_storage_nodes=4
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.minimum_master_nodes=2"
      - "http.cors.allow-origin=*"
      - "http.cors.enabled=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    volumes:
      - ../data:/usr/share/elasticsearch/data
      - ../config:/usr/share/elasticsearch/config
    networks:
      - esnet


  esnode:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - cluster.name=heisenbug
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - node.max_local_storage_nodes=4
      - transport.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=esmaster"
      - "discovery.zen.minimum_master_nodes=2"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    volumes:
      - ../data:/usr/share/elasticsearch/data
      - ../config:/usr/share/elasticsearch/config
    networks:
      - esnet


  cerebro:
    image: yannart/cerebro:latest
    container_name: cerebro
    ports:
      - 9000:9000
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
